version: '3.8'
services:
  mycoverai:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    volumes:
      - .:/src
  mycoverai-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: sensei
      POSTGRES_PASSWORD: sudo123
      POSTGRES_DB: mycoverai
      POSTGRES_HOST: "127.0.0.1"
    networks:
      - mca_network
networks:
  mca_network: