export const SEQUELIZE = 'SEQUELIZE'
export const DEVELOPMENT = 'development'
export const TEST = 'test'
export const PRODUCTION = 'production'
export const USER_REPOSITORY = 'USER_REPOSITORY'
export const POLICY_REPOSITORY = 'POLICY_REPOSITORY'
export const PURCHASE_REPOSITORY = 'PURCHASE_REPOSITORY'